---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-capstone-app
  labels:
    app: devops-capstone-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devops-capstone-app
  template:
    metadata:
      labels:
        app: devops-capstone-app
    spec:
      containers:
      - name: devops-container
        image: 381751878913.dkr.ecr.us-east-1.amazonaws.com/devops-capstone:latest
        ports:
        - containerPort: 3000
...
